# https://zmk.dev/docs/config/system
# 
# Uncomment the following line to enable deep sleep
CONFIG_ZMK_SLEEP=y

# Uncomment the following line to increase the keyboard's wireless range
CONFIG_BT_CTLR_TX_PWR_PLUS_8=n

# Enable eager debouncing
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=1
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=10

# Disable ZMK Studio for Realtime Keymap Updates
CONFIG_ZMK_STUDIO=n
CONFIG_ZMK_STUDIO_LOCKING=n

# Uncomment the following line to enable USB Logging (this increases power usage by a significant amount, turn it off when not in use)
# CONFIG_ZMK_USB_LOGGING=y

CONFIG_ZMK_OSKEY_DEFAULT_OS_WINDOWS=y
#CONFIG_ZMK_OSKEY_DEFAULT_OS_MACOS=y
#CONFIG_ZMK_OSKEY_DEFAULT_OS_LINUX=y

# Enable ZMK as a Bluetooth keyboard
CONFIG_ZMK_BLE=y

# Experimental: require typing passkey from host to pair BLE connection
# NOTE: On macos this leads to successful pairing but needs a reset of the corne
#       afterwards
CONFIG_ZMK_BLE_PASSKEY_ENTRY=n

# Changing this invalidates all BT pairings and needs a
# reset: https://zmk.dev/docs/config/settings#clearing-persisted-settings
# (set CONFIG_ZMK_SETTINGS_RESET_ON_START to y for one build)
CONFIG_ZMK_KEYBOARD_NAME="Cornchen"
CONFIG_ZMK_SETTINGS_RESET_ON_START=n

# Display
# https://zmk.dev/docs/config/displays
# 

# Enable calculating words per minute
# FIXME: This get's ignored
CONFIG_ZMK_WPM=n

# not specifically needed, but
# the nice2 has more than enough power and RAM
CONFIG_ZMK_DISPLAY_WORK_QUEUE_DEDICATED=y
